apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john-doe
  description: Software Engineer at Example Company
  annotations:
    github.com/user-login: johndoe
spec:
  profile:
    displayName: John Doe
    email: john.doe@example.com
    picture: https://example.com/avatar/john-doe.png
  memberOf:
    - team-example
